/*
Kagi API

The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

API version: 0.0.0
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FastGPT200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FastGPT200ResponseData{}

// FastGPT200ResponseData struct for FastGPT200ResponseData
type FastGPT200ResponseData struct {
	Output *string `json:"output,omitempty"`
	Tokens *int32 `json:"tokens,omitempty"`
	References []SearchObject `json:"references,omitempty"`
}

// NewFastGPT200ResponseData instantiates a new FastGPT200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFastGPT200ResponseData() *FastGPT200ResponseData {
	this := FastGPT200ResponseData{}
	return &this
}

// NewFastGPT200ResponseDataWithDefaults instantiates a new FastGPT200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFastGPT200ResponseDataWithDefaults() *FastGPT200ResponseData {
	this := FastGPT200ResponseData{}
	return &this
}

// GetOutput returns the Output field value if set, zero value otherwise.
func (o *FastGPT200ResponseData) GetOutput() string {
	if o == nil || IsNil(o.Output) {
		var ret string
		return ret
	}
	return *o.Output
}

// GetOutputOk returns a tuple with the Output field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FastGPT200ResponseData) GetOutputOk() (*string, bool) {
	if o == nil || IsNil(o.Output) {
		return nil, false
	}
	return o.Output, true
}

// HasOutput returns a boolean if a field has been set.
func (o *FastGPT200ResponseData) HasOutput() bool {
	if o != nil && !IsNil(o.Output) {
		return true
	}

	return false
}

// SetOutput gets a reference to the given string and assigns it to the Output field.
func (o *FastGPT200ResponseData) SetOutput(v string) {
	o.Output = &v
}

// GetTokens returns the Tokens field value if set, zero value otherwise.
func (o *FastGPT200ResponseData) GetTokens() int32 {
	if o == nil || IsNil(o.Tokens) {
		var ret int32
		return ret
	}
	return *o.Tokens
}

// GetTokensOk returns a tuple with the Tokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FastGPT200ResponseData) GetTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.Tokens) {
		return nil, false
	}
	return o.Tokens, true
}

// HasTokens returns a boolean if a field has been set.
func (o *FastGPT200ResponseData) HasTokens() bool {
	if o != nil && !IsNil(o.Tokens) {
		return true
	}

	return false
}

// SetTokens gets a reference to the given int32 and assigns it to the Tokens field.
func (o *FastGPT200ResponseData) SetTokens(v int32) {
	o.Tokens = &v
}

// GetReferences returns the References field value if set, zero value otherwise.
func (o *FastGPT200ResponseData) GetReferences() []SearchObject {
	if o == nil || IsNil(o.References) {
		var ret []SearchObject
		return ret
	}
	return o.References
}

// GetReferencesOk returns a tuple with the References field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FastGPT200ResponseData) GetReferencesOk() ([]SearchObject, bool) {
	if o == nil || IsNil(o.References) {
		return nil, false
	}
	return o.References, true
}

// HasReferences returns a boolean if a field has been set.
func (o *FastGPT200ResponseData) HasReferences() bool {
	if o != nil && !IsNil(o.References) {
		return true
	}

	return false
}

// SetReferences gets a reference to the given []SearchObject and assigns it to the References field.
func (o *FastGPT200ResponseData) SetReferences(v []SearchObject) {
	o.References = v
}

func (o FastGPT200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FastGPT200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Output) {
		toSerialize["output"] = o.Output
	}
	if !IsNil(o.Tokens) {
		toSerialize["tokens"] = o.Tokens
	}
	if !IsNil(o.References) {
		toSerialize["references"] = o.References
	}
	return toSerialize, nil
}

type NullableFastGPT200ResponseData struct {
	value *FastGPT200ResponseData
	isSet bool
}

func (v NullableFastGPT200ResponseData) Get() *FastGPT200ResponseData {
	return v.value
}

func (v *NullableFastGPT200ResponseData) Set(val *FastGPT200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableFastGPT200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableFastGPT200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFastGPT200ResponseData(val *FastGPT200ResponseData) *NullableFastGPT200ResponseData {
	return &NullableFastGPT200ResponseData{value: val, isSet: true}
}

func (v NullableFastGPT200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFastGPT200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


