/*
Kagi API

The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

API version: 0.0.0
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner{}

// TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner struct for TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner
type TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner struct {
	// The repeated word
	Word *string `json:"word,omitempty"`
	// The significance level of the repetition (high, medium, low)
	Significance *string `json:"significance,omitempty"`
}

// NewTranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner instantiates a new TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner() *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner {
	this := TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner{}
	return &this
}

// NewTranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInnerWithDefaults instantiates a new TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInnerWithDefaults() *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner {
	this := TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner{}
	return &this
}

// GetWord returns the Word field value if set, zero value otherwise.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) GetWord() string {
	if o == nil || IsNil(o.Word) {
		var ret string
		return ret
	}
	return *o.Word
}

// GetWordOk returns a tuple with the Word field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) GetWordOk() (*string, bool) {
	if o == nil || IsNil(o.Word) {
		return nil, false
	}
	return o.Word, true
}

// HasWord returns a boolean if a field has been set.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) HasWord() bool {
	if o != nil && !IsNil(o.Word) {
		return true
	}

	return false
}

// SetWord gets a reference to the given string and assigns it to the Word field.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) SetWord(v string) {
	o.Word = &v
}

// GetSignificance returns the Significance field value if set, zero value otherwise.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) GetSignificance() string {
	if o == nil || IsNil(o.Significance) {
		var ret string
		return ret
	}
	return *o.Significance
}

// GetSignificanceOk returns a tuple with the Significance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) GetSignificanceOk() (*string, bool) {
	if o == nil || IsNil(o.Significance) {
		return nil, false
	}
	return o.Significance, true
}

// HasSignificance returns a boolean if a field has been set.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) HasSignificance() bool {
	if o != nil && !IsNil(o.Significance) {
		return true
	}

	return false
}

// SetSignificance gets a reference to the given string and assigns it to the Significance field.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) SetSignificance(v string) {
	o.Significance = &v
}

func (o TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Word) {
		toSerialize["word"] = o.Word
	}
	if !IsNil(o.Significance) {
		toSerialize["significance"] = o.Significance
	}
	return toSerialize, nil
}

type NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner struct {
	value *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner
	isSet bool
}

func (v NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) Get() *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner {
	return v.value
}

func (v *NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) Set(val *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner(val *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) *NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner {
	return &NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner{value: val, isSet: true}
}

func (v NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


