/*
Kagi API

The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

API version: 0.0.0
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TranslateAlternatives402Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranslateAlternatives402Response{}

// TranslateAlternatives402Response struct for TranslateAlternatives402Response
type TranslateAlternatives402Response struct {
	Error *string `json:"error,omitempty"`
}

// NewTranslateAlternatives402Response instantiates a new TranslateAlternatives402Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranslateAlternatives402Response() *TranslateAlternatives402Response {
	this := TranslateAlternatives402Response{}
	return &this
}

// NewTranslateAlternatives402ResponseWithDefaults instantiates a new TranslateAlternatives402Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranslateAlternatives402ResponseWithDefaults() *TranslateAlternatives402Response {
	this := TranslateAlternatives402Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *TranslateAlternatives402Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateAlternatives402Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *TranslateAlternatives402Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *TranslateAlternatives402Response) SetError(v string) {
	o.Error = &v
}

func (o TranslateAlternatives402Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranslateAlternatives402Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableTranslateAlternatives402Response struct {
	value *TranslateAlternatives402Response
	isSet bool
}

func (v NullableTranslateAlternatives402Response) Get() *TranslateAlternatives402Response {
	return v.value
}

func (v *NullableTranslateAlternatives402Response) Set(val *TranslateAlternatives402Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTranslateAlternatives402Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTranslateAlternatives402Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranslateAlternatives402Response(val *TranslateAlternatives402Response) *NullableTranslateAlternatives402Response {
	return &NullableTranslateAlternatives402Response{value: val, isSet: true}
}

func (v NullableTranslateAlternatives402Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranslateAlternatives402Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


