/*
Kagi API

The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

API version: 0.0.0
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExampleError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExampleError{}

// ExampleError I need an example error to appease the linter. Please accept my offering
type ExampleError struct {
	Meta Meta `json:"meta"`
	Error ExampleErrorError `json:"error"`
}

type _ExampleError ExampleError

// NewExampleError instantiates a new ExampleError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExampleError(meta Meta, error_ ExampleErrorError) *ExampleError {
	this := ExampleError{}
	this.Meta = meta
	this.Error = error_
	return &this
}

// NewExampleErrorWithDefaults instantiates a new ExampleError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExampleErrorWithDefaults() *ExampleError {
	this := ExampleError{}
	return &this
}

// GetMeta returns the Meta field value
func (o *ExampleError) GetMeta() Meta {
	if o == nil {
		var ret Meta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *ExampleError) GetMetaOk() (*Meta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *ExampleError) SetMeta(v Meta) {
	o.Meta = v
}

// GetError returns the Error field value
func (o *ExampleError) GetError() ExampleErrorError {
	if o == nil {
		var ret ExampleErrorError
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ExampleError) GetErrorOk() (*ExampleErrorError, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ExampleError) SetError(v ExampleErrorError) {
	o.Error = v
}

func (o ExampleError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExampleError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["meta"] = o.Meta
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *ExampleError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"meta",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExampleError := _ExampleError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExampleError)

	if err != nil {
		return err
	}

	*o = ExampleError(varExampleError)

	return err
}

type NullableExampleError struct {
	value *ExampleError
	isSet bool
}

func (v NullableExampleError) Get() *ExampleError {
	return v.value
}

func (v *NullableExampleError) Set(val *ExampleError) {
	v.value = val
	v.isSet = true
}

func (v NullableExampleError) IsSet() bool {
	return v.isSet
}

func (v *NullableExampleError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExampleError(val *ExampleError) *NullableExampleError {
	return &NullableExampleError{value: val, isSet: true}
}

func (v NullableExampleError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExampleError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


