/*
Kagi API

The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

API version: 0.0.0
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TranslateWordInsights200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranslateWordInsights200Response{}

// TranslateWordInsights200Response struct for TranslateWordInsights200Response
type TranslateWordInsights200Response struct {
	// The translated text with markers (<<INSIGHT_N>>) indicating insight locations
	MarkedTranslation *string `json:"marked_translation,omitempty"`
	Insights []TranslateWordInsights200ResponseInsightsInner `json:"insights,omitempty"`
}

// NewTranslateWordInsights200Response instantiates a new TranslateWordInsights200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranslateWordInsights200Response() *TranslateWordInsights200Response {
	this := TranslateWordInsights200Response{}
	return &this
}

// NewTranslateWordInsights200ResponseWithDefaults instantiates a new TranslateWordInsights200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranslateWordInsights200ResponseWithDefaults() *TranslateWordInsights200Response {
	this := TranslateWordInsights200Response{}
	return &this
}

// GetMarkedTranslation returns the MarkedTranslation field value if set, zero value otherwise.
func (o *TranslateWordInsights200Response) GetMarkedTranslation() string {
	if o == nil || IsNil(o.MarkedTranslation) {
		var ret string
		return ret
	}
	return *o.MarkedTranslation
}

// GetMarkedTranslationOk returns a tuple with the MarkedTranslation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateWordInsights200Response) GetMarkedTranslationOk() (*string, bool) {
	if o == nil || IsNil(o.MarkedTranslation) {
		return nil, false
	}
	return o.MarkedTranslation, true
}

// HasMarkedTranslation returns a boolean if a field has been set.
func (o *TranslateWordInsights200Response) HasMarkedTranslation() bool {
	if o != nil && !IsNil(o.MarkedTranslation) {
		return true
	}

	return false
}

// SetMarkedTranslation gets a reference to the given string and assigns it to the MarkedTranslation field.
func (o *TranslateWordInsights200Response) SetMarkedTranslation(v string) {
	o.MarkedTranslation = &v
}

// GetInsights returns the Insights field value if set, zero value otherwise.
func (o *TranslateWordInsights200Response) GetInsights() []TranslateWordInsights200ResponseInsightsInner {
	if o == nil || IsNil(o.Insights) {
		var ret []TranslateWordInsights200ResponseInsightsInner
		return ret
	}
	return o.Insights
}

// GetInsightsOk returns a tuple with the Insights field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateWordInsights200Response) GetInsightsOk() ([]TranslateWordInsights200ResponseInsightsInner, bool) {
	if o == nil || IsNil(o.Insights) {
		return nil, false
	}
	return o.Insights, true
}

// HasInsights returns a boolean if a field has been set.
func (o *TranslateWordInsights200Response) HasInsights() bool {
	if o != nil && !IsNil(o.Insights) {
		return true
	}

	return false
}

// SetInsights gets a reference to the given []TranslateWordInsights200ResponseInsightsInner and assigns it to the Insights field.
func (o *TranslateWordInsights200Response) SetInsights(v []TranslateWordInsights200ResponseInsightsInner) {
	o.Insights = v
}

func (o TranslateWordInsights200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranslateWordInsights200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MarkedTranslation) {
		toSerialize["marked_translation"] = o.MarkedTranslation
	}
	if !IsNil(o.Insights) {
		toSerialize["insights"] = o.Insights
	}
	return toSerialize, nil
}

type NullableTranslateWordInsights200Response struct {
	value *TranslateWordInsights200Response
	isSet bool
}

func (v NullableTranslateWordInsights200Response) Get() *TranslateWordInsights200Response {
	return v.value
}

func (v *NullableTranslateWordInsights200Response) Set(val *TranslateWordInsights200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTranslateWordInsights200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTranslateWordInsights200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranslateWordInsights200Response(val *TranslateWordInsights200Response) *NullableTranslateWordInsights200Response {
	return &NullableTranslateWordInsights200Response{value: val, isSet: true}
}

func (v NullableTranslateWordInsights200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranslateWordInsights200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


