/*
Kagi API

The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

API version: 0.0.0
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExampleErrorError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExampleErrorError{}

// ExampleErrorError struct for ExampleErrorError
type ExampleErrorError struct {
	Code int32 `json:"code"`
	Msg string `json:"msg"`
	Ref *string `json:"ref,omitempty"`
}

type _ExampleErrorError ExampleErrorError

// NewExampleErrorError instantiates a new ExampleErrorError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExampleErrorError(code int32, msg string) *ExampleErrorError {
	this := ExampleErrorError{}
	this.Code = code
	this.Msg = msg
	return &this
}

// NewExampleErrorErrorWithDefaults instantiates a new ExampleErrorError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExampleErrorErrorWithDefaults() *ExampleErrorError {
	this := ExampleErrorError{}
	return &this
}

// GetCode returns the Code field value
func (o *ExampleErrorError) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ExampleErrorError) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ExampleErrorError) SetCode(v int32) {
	o.Code = v
}

// GetMsg returns the Msg field value
func (o *ExampleErrorError) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *ExampleErrorError) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *ExampleErrorError) SetMsg(v string) {
	o.Msg = v
}

// GetRef returns the Ref field value if set, zero value otherwise.
func (o *ExampleErrorError) GetRef() string {
	if o == nil || IsNil(o.Ref) {
		var ret string
		return ret
	}
	return *o.Ref
}

// GetRefOk returns a tuple with the Ref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExampleErrorError) GetRefOk() (*string, bool) {
	if o == nil || IsNil(o.Ref) {
		return nil, false
	}
	return o.Ref, true
}

// HasRef returns a boolean if a field has been set.
func (o *ExampleErrorError) HasRef() bool {
	if o != nil && !IsNil(o.Ref) {
		return true
	}

	return false
}

// SetRef gets a reference to the given string and assigns it to the Ref field.
func (o *ExampleErrorError) SetRef(v string) {
	o.Ref = &v
}

func (o ExampleErrorError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExampleErrorError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["msg"] = o.Msg
	if !IsNil(o.Ref) {
		toSerialize["ref"] = o.Ref
	}
	return toSerialize, nil
}

func (o *ExampleErrorError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"msg",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExampleErrorError := _ExampleErrorError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExampleErrorError)

	if err != nil {
		return err
	}

	*o = ExampleErrorError(varExampleErrorError)

	return err
}

type NullableExampleErrorError struct {
	value *ExampleErrorError
	isSet bool
}

func (v NullableExampleErrorError) Get() *ExampleErrorError {
	return v.value
}

func (v *NullableExampleErrorError) Set(val *ExampleErrorError) {
	v.value = val
	v.isSet = true
}

func (v NullableExampleErrorError) IsSet() bool {
	return v.isSet
}

func (v *NullableExampleErrorError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExampleErrorError(val *ExampleErrorError) *NullableExampleErrorError {
	return &NullableExampleErrorError{value: val, isSet: true}
}

func (v NullableExampleErrorError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExampleErrorError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


