/*
Kagi API

The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

API version: 0.0.0
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TranslateDictionary200ResponseLanguage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranslateDictionary200ResponseLanguage{}

// TranslateDictionary200ResponseLanguage struct for TranslateDictionary200ResponseLanguage
type TranslateDictionary200ResponseLanguage struct {
	// ISO code of the language
	Iso *string `json:"iso,omitempty"`
	// Human-readable language name
	Label *string `json:"label,omitempty"`
}

// NewTranslateDictionary200ResponseLanguage instantiates a new TranslateDictionary200ResponseLanguage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranslateDictionary200ResponseLanguage() *TranslateDictionary200ResponseLanguage {
	this := TranslateDictionary200ResponseLanguage{}
	return &this
}

// NewTranslateDictionary200ResponseLanguageWithDefaults instantiates a new TranslateDictionary200ResponseLanguage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranslateDictionary200ResponseLanguageWithDefaults() *TranslateDictionary200ResponseLanguage {
	this := TranslateDictionary200ResponseLanguage{}
	return &this
}

// GetIso returns the Iso field value if set, zero value otherwise.
func (o *TranslateDictionary200ResponseLanguage) GetIso() string {
	if o == nil || IsNil(o.Iso) {
		var ret string
		return ret
	}
	return *o.Iso
}

// GetIsoOk returns a tuple with the Iso field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateDictionary200ResponseLanguage) GetIsoOk() (*string, bool) {
	if o == nil || IsNil(o.Iso) {
		return nil, false
	}
	return o.Iso, true
}

// HasIso returns a boolean if a field has been set.
func (o *TranslateDictionary200ResponseLanguage) HasIso() bool {
	if o != nil && !IsNil(o.Iso) {
		return true
	}

	return false
}

// SetIso gets a reference to the given string and assigns it to the Iso field.
func (o *TranslateDictionary200ResponseLanguage) SetIso(v string) {
	o.Iso = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *TranslateDictionary200ResponseLanguage) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateDictionary200ResponseLanguage) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *TranslateDictionary200ResponseLanguage) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *TranslateDictionary200ResponseLanguage) SetLabel(v string) {
	o.Label = &v
}

func (o TranslateDictionary200ResponseLanguage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranslateDictionary200ResponseLanguage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Iso) {
		toSerialize["iso"] = o.Iso
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableTranslateDictionary200ResponseLanguage struct {
	value *TranslateDictionary200ResponseLanguage
	isSet bool
}

func (v NullableTranslateDictionary200ResponseLanguage) Get() *TranslateDictionary200ResponseLanguage {
	return v.value
}

func (v *NullableTranslateDictionary200ResponseLanguage) Set(val *TranslateDictionary200ResponseLanguage) {
	v.value = val
	v.isSet = true
}

func (v NullableTranslateDictionary200ResponseLanguage) IsSet() bool {
	return v.isSet
}

func (v *NullableTranslateDictionary200ResponseLanguage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranslateDictionary200ResponseLanguage(val *TranslateDictionary200ResponseLanguage) *NullableTranslateDictionary200ResponseLanguage {
	return &NullableTranslateDictionary200ResponseLanguage{value: val, isSet: true}
}

func (v NullableTranslateDictionary200ResponseLanguage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranslateDictionary200ResponseLanguage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


