/*
Kagi API

The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

API version: 0.0.0
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TranslateWordInsights200ResponseInsightsInnerVariationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranslateWordInsights200ResponseInsightsInnerVariationsInner{}

// TranslateWordInsights200ResponseInsightsInnerVariationsInner struct for TranslateWordInsights200ResponseInsightsInnerVariationsInner
type TranslateWordInsights200ResponseInsightsInnerVariationsInner struct {
	// Alternative word or phrase in the target language
	Text *string `json:"text,omitempty"`
	// Brief explanation of usage/nuance in the explanation language
	Explanation *string `json:"explanation,omitempty"`
}

// NewTranslateWordInsights200ResponseInsightsInnerVariationsInner instantiates a new TranslateWordInsights200ResponseInsightsInnerVariationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranslateWordInsights200ResponseInsightsInnerVariationsInner() *TranslateWordInsights200ResponseInsightsInnerVariationsInner {
	this := TranslateWordInsights200ResponseInsightsInnerVariationsInner{}
	return &this
}

// NewTranslateWordInsights200ResponseInsightsInnerVariationsInnerWithDefaults instantiates a new TranslateWordInsights200ResponseInsightsInnerVariationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranslateWordInsights200ResponseInsightsInnerVariationsInnerWithDefaults() *TranslateWordInsights200ResponseInsightsInnerVariationsInner {
	this := TranslateWordInsights200ResponseInsightsInnerVariationsInner{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *TranslateWordInsights200ResponseInsightsInnerVariationsInner) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateWordInsights200ResponseInsightsInnerVariationsInner) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *TranslateWordInsights200ResponseInsightsInnerVariationsInner) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *TranslateWordInsights200ResponseInsightsInnerVariationsInner) SetText(v string) {
	o.Text = &v
}

// GetExplanation returns the Explanation field value if set, zero value otherwise.
func (o *TranslateWordInsights200ResponseInsightsInnerVariationsInner) GetExplanation() string {
	if o == nil || IsNil(o.Explanation) {
		var ret string
		return ret
	}
	return *o.Explanation
}

// GetExplanationOk returns a tuple with the Explanation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateWordInsights200ResponseInsightsInnerVariationsInner) GetExplanationOk() (*string, bool) {
	if o == nil || IsNil(o.Explanation) {
		return nil, false
	}
	return o.Explanation, true
}

// HasExplanation returns a boolean if a field has been set.
func (o *TranslateWordInsights200ResponseInsightsInnerVariationsInner) HasExplanation() bool {
	if o != nil && !IsNil(o.Explanation) {
		return true
	}

	return false
}

// SetExplanation gets a reference to the given string and assigns it to the Explanation field.
func (o *TranslateWordInsights200ResponseInsightsInnerVariationsInner) SetExplanation(v string) {
	o.Explanation = &v
}

func (o TranslateWordInsights200ResponseInsightsInnerVariationsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranslateWordInsights200ResponseInsightsInnerVariationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Explanation) {
		toSerialize["explanation"] = o.Explanation
	}
	return toSerialize, nil
}

type NullableTranslateWordInsights200ResponseInsightsInnerVariationsInner struct {
	value *TranslateWordInsights200ResponseInsightsInnerVariationsInner
	isSet bool
}

func (v NullableTranslateWordInsights200ResponseInsightsInnerVariationsInner) Get() *TranslateWordInsights200ResponseInsightsInnerVariationsInner {
	return v.value
}

func (v *NullableTranslateWordInsights200ResponseInsightsInnerVariationsInner) Set(val *TranslateWordInsights200ResponseInsightsInnerVariationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTranslateWordInsights200ResponseInsightsInnerVariationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTranslateWordInsights200ResponseInsightsInnerVariationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranslateWordInsights200ResponseInsightsInnerVariationsInner(val *TranslateWordInsights200ResponseInsightsInnerVariationsInner) *NullableTranslateWordInsights200ResponseInsightsInnerVariationsInner {
	return &NullableTranslateWordInsights200ResponseInsightsInnerVariationsInner{value: val, isSet: true}
}

func (v NullableTranslateWordInsights200ResponseInsightsInnerVariationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranslateWordInsights200ResponseInsightsInnerVariationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


