/*
Kagi API

The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

API version: 0.0.0
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner{}

// TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner struct for TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner
type TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner struct {
	// The repeated phrase
	Phrase *string `json:"phrase,omitempty"`
	// The significance level of the repetition (high, medium, low)
	Significance *string `json:"significance,omitempty"`
}

// NewTranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner instantiates a new TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner() *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner {
	this := TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner{}
	return &this
}

// NewTranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInnerWithDefaults instantiates a new TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInnerWithDefaults() *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner {
	this := TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner{}
	return &this
}

// GetPhrase returns the Phrase field value if set, zero value otherwise.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) GetPhrase() string {
	if o == nil || IsNil(o.Phrase) {
		var ret string
		return ret
	}
	return *o.Phrase
}

// GetPhraseOk returns a tuple with the Phrase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) GetPhraseOk() (*string, bool) {
	if o == nil || IsNil(o.Phrase) {
		return nil, false
	}
	return o.Phrase, true
}

// HasPhrase returns a boolean if a field has been set.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) HasPhrase() bool {
	if o != nil && !IsNil(o.Phrase) {
		return true
	}

	return false
}

// SetPhrase gets a reference to the given string and assigns it to the Phrase field.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) SetPhrase(v string) {
	o.Phrase = &v
}

// GetSignificance returns the Significance field value if set, zero value otherwise.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) GetSignificance() string {
	if o == nil || IsNil(o.Significance) {
		var ret string
		return ret
	}
	return *o.Significance
}

// GetSignificanceOk returns a tuple with the Significance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) GetSignificanceOk() (*string, bool) {
	if o == nil || IsNil(o.Significance) {
		return nil, false
	}
	return o.Significance, true
}

// HasSignificance returns a boolean if a field has been set.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) HasSignificance() bool {
	if o != nil && !IsNil(o.Significance) {
		return true
	}

	return false
}

// SetSignificance gets a reference to the given string and assigns it to the Significance field.
func (o *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) SetSignificance(v string) {
	o.Significance = &v
}

func (o TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Phrase) {
		toSerialize["phrase"] = o.Phrase
	}
	if !IsNil(o.Significance) {
		toSerialize["significance"] = o.Significance
	}
	return toSerialize, nil
}

type NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner struct {
	value *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner
	isSet bool
}

func (v NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) Get() *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner {
	return v.value
}

func (v *NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) Set(val *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner(val *TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) *NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner {
	return &NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner{value: val, isSet: true}
}

func (v NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


