/*
Kagi API

The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

API version: 0.0.0
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TranslateTextAlignments200ResponseAlignmentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranslateTextAlignments200ResponseAlignmentsInner{}

// TranslateTextAlignments200ResponseAlignmentsInner struct for TranslateTextAlignments200ResponseAlignmentsInner
type TranslateTextAlignments200ResponseAlignmentsInner struct {
	// Source text segment
	Source *string `json:"source,omitempty"`
	// Corresponding target text segment
	Target *string `json:"target,omitempty"`
}

// NewTranslateTextAlignments200ResponseAlignmentsInner instantiates a new TranslateTextAlignments200ResponseAlignmentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranslateTextAlignments200ResponseAlignmentsInner() *TranslateTextAlignments200ResponseAlignmentsInner {
	this := TranslateTextAlignments200ResponseAlignmentsInner{}
	return &this
}

// NewTranslateTextAlignments200ResponseAlignmentsInnerWithDefaults instantiates a new TranslateTextAlignments200ResponseAlignmentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranslateTextAlignments200ResponseAlignmentsInnerWithDefaults() *TranslateTextAlignments200ResponseAlignmentsInner {
	this := TranslateTextAlignments200ResponseAlignmentsInner{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *TranslateTextAlignments200ResponseAlignmentsInner) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateTextAlignments200ResponseAlignmentsInner) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *TranslateTextAlignments200ResponseAlignmentsInner) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *TranslateTextAlignments200ResponseAlignmentsInner) SetSource(v string) {
	o.Source = &v
}

// GetTarget returns the Target field value if set, zero value otherwise.
func (o *TranslateTextAlignments200ResponseAlignmentsInner) GetTarget() string {
	if o == nil || IsNil(o.Target) {
		var ret string
		return ret
	}
	return *o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateTextAlignments200ResponseAlignmentsInner) GetTargetOk() (*string, bool) {
	if o == nil || IsNil(o.Target) {
		return nil, false
	}
	return o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *TranslateTextAlignments200ResponseAlignmentsInner) HasTarget() bool {
	if o != nil && !IsNil(o.Target) {
		return true
	}

	return false
}

// SetTarget gets a reference to the given string and assigns it to the Target field.
func (o *TranslateTextAlignments200ResponseAlignmentsInner) SetTarget(v string) {
	o.Target = &v
}

func (o TranslateTextAlignments200ResponseAlignmentsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranslateTextAlignments200ResponseAlignmentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Target) {
		toSerialize["target"] = o.Target
	}
	return toSerialize, nil
}

type NullableTranslateTextAlignments200ResponseAlignmentsInner struct {
	value *TranslateTextAlignments200ResponseAlignmentsInner
	isSet bool
}

func (v NullableTranslateTextAlignments200ResponseAlignmentsInner) Get() *TranslateTextAlignments200ResponseAlignmentsInner {
	return v.value
}

func (v *NullableTranslateTextAlignments200ResponseAlignmentsInner) Set(val *TranslateTextAlignments200ResponseAlignmentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTranslateTextAlignments200ResponseAlignmentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTranslateTextAlignments200ResponseAlignmentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranslateTextAlignments200ResponseAlignmentsInner(val *TranslateTextAlignments200ResponseAlignmentsInner) *NullableTranslateTextAlignments200ResponseAlignmentsInner {
	return &NullableTranslateTextAlignments200ResponseAlignmentsInner{value: val, isSet: true}
}

func (v NullableTranslateTextAlignments200ResponseAlignmentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranslateTextAlignments200ResponseAlignmentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


