/*
Kagi API

The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

API version: 0.0.0
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner{}

// TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner struct for TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner
type TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner struct {
	// The passive voice construction
	Passive *string `json:"passive,omitempty"`
	// Suggested active voice alternative
	ActiveAlternative *string `json:"active_alternative,omitempty"`
}

// NewTranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner instantiates a new TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner() *TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner {
	this := TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner{}
	return &this
}

// NewTranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInnerWithDefaults instantiates a new TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInnerWithDefaults() *TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner {
	this := TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner{}
	return &this
}

// GetPassive returns the Passive field value if set, zero value otherwise.
func (o *TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) GetPassive() string {
	if o == nil || IsNil(o.Passive) {
		var ret string
		return ret
	}
	return *o.Passive
}

// GetPassiveOk returns a tuple with the Passive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) GetPassiveOk() (*string, bool) {
	if o == nil || IsNil(o.Passive) {
		return nil, false
	}
	return o.Passive, true
}

// HasPassive returns a boolean if a field has been set.
func (o *TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) HasPassive() bool {
	if o != nil && !IsNil(o.Passive) {
		return true
	}

	return false
}

// SetPassive gets a reference to the given string and assigns it to the Passive field.
func (o *TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) SetPassive(v string) {
	o.Passive = &v
}

// GetActiveAlternative returns the ActiveAlternative field value if set, zero value otherwise.
func (o *TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) GetActiveAlternative() string {
	if o == nil || IsNil(o.ActiveAlternative) {
		var ret string
		return ret
	}
	return *o.ActiveAlternative
}

// GetActiveAlternativeOk returns a tuple with the ActiveAlternative field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) GetActiveAlternativeOk() (*string, bool) {
	if o == nil || IsNil(o.ActiveAlternative) {
		return nil, false
	}
	return o.ActiveAlternative, true
}

// HasActiveAlternative returns a boolean if a field has been set.
func (o *TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) HasActiveAlternative() bool {
	if o != nil && !IsNil(o.ActiveAlternative) {
		return true
	}

	return false
}

// SetActiveAlternative gets a reference to the given string and assigns it to the ActiveAlternative field.
func (o *TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) SetActiveAlternative(v string) {
	o.ActiveAlternative = &v
}

func (o TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Passive) {
		toSerialize["passive"] = o.Passive
	}
	if !IsNil(o.ActiveAlternative) {
		toSerialize["active_alternative"] = o.ActiveAlternative
	}
	return toSerialize, nil
}

type NullableTranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner struct {
	value *TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner
	isSet bool
}

func (v NullableTranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) Get() *TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner {
	return v.value
}

func (v *NullableTranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) Set(val *TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner(val *TranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) *NullableTranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner {
	return &NullableTranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner{value: val, isSet: true}
}

func (v NullableTranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranslateProofReadGet200ResponseVoiceConsistencyPassiveInstancesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


