/*
Kagi API

The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

API version: 0.0.0
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TranslateDetectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranslateDetectRequest{}

// TranslateDetectRequest struct for TranslateDetectRequest
type TranslateDetectRequest struct {
	// Text to detect language from
	Text string `json:"text"`
}

type _TranslateDetectRequest TranslateDetectRequest

// NewTranslateDetectRequest instantiates a new TranslateDetectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranslateDetectRequest(text string) *TranslateDetectRequest {
	this := TranslateDetectRequest{}
	this.Text = text
	return &this
}

// NewTranslateDetectRequestWithDefaults instantiates a new TranslateDetectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranslateDetectRequestWithDefaults() *TranslateDetectRequest {
	this := TranslateDetectRequest{}
	return &this
}

// GetText returns the Text field value
func (o *TranslateDetectRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *TranslateDetectRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *TranslateDetectRequest) SetText(v string) {
	o.Text = v
}

func (o TranslateDetectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranslateDetectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *TranslateDetectRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTranslateDetectRequest := _TranslateDetectRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTranslateDetectRequest)

	if err != nil {
		return err
	}

	*o = TranslateDetectRequest(varTranslateDetectRequest)

	return err
}

type NullableTranslateDetectRequest struct {
	value *TranslateDetectRequest
	isSet bool
}

func (v NullableTranslateDetectRequest) Get() *TranslateDetectRequest {
	return v.value
}

func (v *NullableTranslateDetectRequest) Set(val *TranslateDetectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTranslateDetectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTranslateDetectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranslateDetectRequest(val *TranslateDetectRequest) *NullableTranslateDetectRequest {
	return &NullableTranslateDetectRequest{value: val, isSet: true}
}

func (v NullableTranslateDetectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranslateDetectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


