/*
Kagi API

The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

API version: 0.0.0
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TranslateProofReadGet200ResponseRepetitionDetection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranslateProofReadGet200ResponseRepetitionDetection{}

// TranslateProofReadGet200ResponseRepetitionDetection Analysis of repeated words and phrases
type TranslateProofReadGet200ResponseRepetitionDetection struct {
	// Words that appear frequently in the text
	RepeatedWords []TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner `json:"repeated_words,omitempty"`
	// Phrases that appear frequently in the text
	RepeatedPhrases []TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner `json:"repeated_phrases,omitempty"`
	// Overall assessment of word/phrase repetition and its impact
	Summary *string `json:"summary,omitempty"`
}

// NewTranslateProofReadGet200ResponseRepetitionDetection instantiates a new TranslateProofReadGet200ResponseRepetitionDetection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranslateProofReadGet200ResponseRepetitionDetection() *TranslateProofReadGet200ResponseRepetitionDetection {
	this := TranslateProofReadGet200ResponseRepetitionDetection{}
	return &this
}

// NewTranslateProofReadGet200ResponseRepetitionDetectionWithDefaults instantiates a new TranslateProofReadGet200ResponseRepetitionDetection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranslateProofReadGet200ResponseRepetitionDetectionWithDefaults() *TranslateProofReadGet200ResponseRepetitionDetection {
	this := TranslateProofReadGet200ResponseRepetitionDetection{}
	return &this
}

// GetRepeatedWords returns the RepeatedWords field value if set, zero value otherwise.
func (o *TranslateProofReadGet200ResponseRepetitionDetection) GetRepeatedWords() []TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner {
	if o == nil || IsNil(o.RepeatedWords) {
		var ret []TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner
		return ret
	}
	return o.RepeatedWords
}

// GetRepeatedWordsOk returns a tuple with the RepeatedWords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateProofReadGet200ResponseRepetitionDetection) GetRepeatedWordsOk() ([]TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner, bool) {
	if o == nil || IsNil(o.RepeatedWords) {
		return nil, false
	}
	return o.RepeatedWords, true
}

// HasRepeatedWords returns a boolean if a field has been set.
func (o *TranslateProofReadGet200ResponseRepetitionDetection) HasRepeatedWords() bool {
	if o != nil && !IsNil(o.RepeatedWords) {
		return true
	}

	return false
}

// SetRepeatedWords gets a reference to the given []TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner and assigns it to the RepeatedWords field.
func (o *TranslateProofReadGet200ResponseRepetitionDetection) SetRepeatedWords(v []TranslateProofReadGet200ResponseRepetitionDetectionRepeatedWordsInner) {
	o.RepeatedWords = v
}

// GetRepeatedPhrases returns the RepeatedPhrases field value if set, zero value otherwise.
func (o *TranslateProofReadGet200ResponseRepetitionDetection) GetRepeatedPhrases() []TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner {
	if o == nil || IsNil(o.RepeatedPhrases) {
		var ret []TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner
		return ret
	}
	return o.RepeatedPhrases
}

// GetRepeatedPhrasesOk returns a tuple with the RepeatedPhrases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateProofReadGet200ResponseRepetitionDetection) GetRepeatedPhrasesOk() ([]TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner, bool) {
	if o == nil || IsNil(o.RepeatedPhrases) {
		return nil, false
	}
	return o.RepeatedPhrases, true
}

// HasRepeatedPhrases returns a boolean if a field has been set.
func (o *TranslateProofReadGet200ResponseRepetitionDetection) HasRepeatedPhrases() bool {
	if o != nil && !IsNil(o.RepeatedPhrases) {
		return true
	}

	return false
}

// SetRepeatedPhrases gets a reference to the given []TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner and assigns it to the RepeatedPhrases field.
func (o *TranslateProofReadGet200ResponseRepetitionDetection) SetRepeatedPhrases(v []TranslateProofReadGet200ResponseRepetitionDetectionRepeatedPhrasesInner) {
	o.RepeatedPhrases = v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *TranslateProofReadGet200ResponseRepetitionDetection) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranslateProofReadGet200ResponseRepetitionDetection) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *TranslateProofReadGet200ResponseRepetitionDetection) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *TranslateProofReadGet200ResponseRepetitionDetection) SetSummary(v string) {
	o.Summary = &v
}

func (o TranslateProofReadGet200ResponseRepetitionDetection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranslateProofReadGet200ResponseRepetitionDetection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RepeatedWords) {
		toSerialize["repeated_words"] = o.RepeatedWords
	}
	if !IsNil(o.RepeatedPhrases) {
		toSerialize["repeated_phrases"] = o.RepeatedPhrases
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	return toSerialize, nil
}

type NullableTranslateProofReadGet200ResponseRepetitionDetection struct {
	value *TranslateProofReadGet200ResponseRepetitionDetection
	isSet bool
}

func (v NullableTranslateProofReadGet200ResponseRepetitionDetection) Get() *TranslateProofReadGet200ResponseRepetitionDetection {
	return v.value
}

func (v *NullableTranslateProofReadGet200ResponseRepetitionDetection) Set(val *TranslateProofReadGet200ResponseRepetitionDetection) {
	v.value = val
	v.isSet = true
}

func (v NullableTranslateProofReadGet200ResponseRepetitionDetection) IsSet() bool {
	return v.isSet
}

func (v *NullableTranslateProofReadGet200ResponseRepetitionDetection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranslateProofReadGet200ResponseRepetitionDetection(val *TranslateProofReadGet200ResponseRepetitionDetection) *NullableTranslateProofReadGet200ResponseRepetitionDetection {
	return &NullableTranslateProofReadGet200ResponseRepetitionDetection{value: val, isSet: true}
}

func (v NullableTranslateProofReadGet200ResponseRepetitionDetection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranslateProofReadGet200ResponseRepetitionDetection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


